{
 "title": "Quarkus Metrics Dashboard-",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "Converted Names",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_org_acme_people_stream_NameConverter_convertedNames_total"
    }
   ]
  },
  {
   "title": "Converter Performance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_org_acme_people_stream_NameConverter_converter_seconds_count"
    }
   ]
  }
 ]
}